version: "3.1"

services:

  db:
    image: postgres:12-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: Ordering_System
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 666666